version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/medical_insights
    command: ["tail", "-f", "/dev/null"]

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=medical_insights
