version: 2

models:
  - name: dim_channels
    description: "Dimension table for Telegram channels."
    columns:
      - name: channel_name
        description: "Name of the Telegram channel."
        tests:
          - unique
          - not_null
      - name: channel_sk
        description: "Surrogate key for the channel."
        tests:
          - unique
          - not_null

  - name: dim_dates
    description: "Dimension table for dates."
    columns:
      - name: date_day
        description: "The date."
        tests:
          - unique
          - not_null

  - name: fct_messages
    description: "Fact table for Telegram messages, linking to dimensions."
    columns:
      - name: message_pk
        description: "Primary key for the message fact."
        tests:
          - not_null
      - name: message_id
        description: "Original Telegram message ID."
        tests:
          - not_null
      - name: channel_sk
        description: "Foreign key to dim_channels."
        tests:
          - not_null
          - relationships:
              to: ref('dim_channels')
              field: channel_sk
      - name: message_date_key
        description: "Foreign key to dim_dates."
        tests:
          - not_null
          - relationships:
              to: ref('dim_dates')
              field: date_day
      - name: message_length
        description: "Length of the message text."
      - name: has_photo
        description: "Boolean indicating if the message contains a photo."
      - name: product_mentions
        description: "Array of product or drug mentions extracted from the message."

  - name: fct_image_detections
    description: "Fact table for YOLOv8 image detection results."
    columns:
      - name: detection_pk
        description: "Surrogate key for the detection record."
        tests:
          - unique
          - not_null
      - name: message_id
        description: "Foreign key to fct_messages (original Telegram message)."
        tests:
          - not_null
      - name: image_id
        description: "Image identifier (if available)."
      - name: object_class
        description: "Detected object class (e.g., pill, cream)."
        tests:
          - not_null
      - name: confidence_score
        description: "YOLOv8 confidence score for the detection."
      - name: detection_time
        description: "Timestamp when detection was performed."