name: 'medical_dbt'
version: '1.0.0'
config-version: 2

profile: 'medical_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  medical_dbt:
    +materialized: view